package.json
src/providers/sidebar-provider/sidebar-tree-items.ts

Here's the pull request that adds a configuration option to enable or disable default expanding table columns on first load.
Related to issue https://github.com/mtxr/vscode-sqltools/issues/105

Add option to disable or enable table columns collapse on first load

---

.vscode/tasks.json
packages/core/dialect/oracle/index.ts
packages/core/dialect/oracle/queries.ts

- added isPK and isFG property
- changed tables select to only tables owned by current user (https://github.com/mtxr/vscode-sqltools/issues/139). Selecting for all tables with addition to joining with constraints info takes quite some time for larger databases.
- bacground property in the tasks.json was in the wrong place
- fetch date and clob datatypes as string
@mtxr , icons are not visible in my case, is there anything else i should do to display them? Also when connecion is active, there is an icon missing in my case.

Oracle: Add PK and FG properties

---

packages/core/dialect/oracle/index.ts
packages/plugins/connection-manager/explorer/tree-items.ts
packages/plugins/connection-manager/screens/provider.ts

`Uri.parse('file...` is causing problems with icon paths .

Fix icon paths (active db, pk, fk)

---

docs/Connections/SQLite.md

Adding more prominent documentation about SQLite setup that many people seem to miss regarding the `sqltools.useNodeRuntime` setting. Added a sample `settings.json`.

Improve SQLite setup docs

---

.test-database/.vscode/settings.json
CHANGELOG.md
docs/Connections/OracleDB.md
packages/core/dialect/oracle/index.ts
packages/core/interface/connection.ts
packages/core/utils/errors.ts
packages/extension/package.json

ORA: Add pool configuration (oracleOptions)

---

docs/Connections/postgresql.md

First up - awesome project thanks for all the hard work!
I hit a bit of a stumbling block around how to use the SSL option when connecting to an Azure Postgres DB. The [docs linked here](https://node-postgres.com/features/ssl) show how to specify a cert but I just need to ensure it was enabled. 
To help others I added a quick example to the docs - hope this is useful, let me know if it needs tweaking and no worries if you don't want to include.

Add SSL example to Postgres docs

---

packages/plugins/connection-manager/screens/settings.ts

Fixes #241 to make the database connection config relative to the workspace.
----

Make database configuration relative to the workspace root

---

packages/core/dialect/saphana/index.ts
packages/core/dialect/saphana/queries.ts

With this PR, the SAP HANA dialect also shows views (not only tables) in a given connection 
----

Support views of HANA

---

docs/Contributing/building.md

Added a little clarification for the building guide requiring yarn (with node and npm being more implicit, but still worth mentioning) to build successfully.

Amend the building guide

---

packages/core/dialect/mssql/queries.ts

Changing the queries to be compatible with MSSQL Server 2000 (v8.x), replacing _CONCAT_ with _ISNULL(string, '') + next string_ and _STRING_AGG_ with a _COALESCE(STUFF(ISNULL()))_ mix.
Closes #418

Changing queries to be compatible with MSSQL2000

---

packages/core/dialect/mssql/queries.ts

Forgot to clean comma from removed column and the very CONCAT used as an example in #440, was not converted using the ISNULL() approach.

Cleanup from removed column and overlooked CONCAT

---

packages/core/dialect/mysql/xprotocol.ts

Fix https://github.com/mtxr/vscode-sqltools/issues/447
A recent commit in @mysql/xdevapi (https://github.com/mysql/mysql-connector-nodejs/commit/a49b47d89e9710efc6cffd727072ceff37058a22#diff-0fe2d532ca52cfbcb0ee51b0a150d0bfL36) changed the return type of `SqlExecute` from [`Result`](https://dev.mysql.com/doc/dev/connector-nodejs/8.0/module-Result.html) to [`SqlResult`](https://dev.mysql.com/doc/dev/connector-nodejs/8.0/module-SqlResult.html). Since there's no api to get information of affected rows in `SqlResult`, I simply removed the logging of affected rows. 
----

Remove call of getAffectedRowsCount

---

docs/src/pages/features/session-multiple-connections.mdx
packages/extension/package.json
packages/plugins/connection-manager/extension.ts
packages/types/settings/index.d.ts
test/project.code-workspace

Addresses https://github.com/mtxr/vscode-sqltools/issues/497
Adds the ability to specify a folder for session files to be saved in when hitting `Ctrl-S` vs the root of the repo.
----

Add ability to specify a folder for session files

---

packages/drivers/src/driver/cql/index.ts
test/docker/cql/1.create-some-stuff.sql
test/docker/cql/Dockerfile.cassandra
test/docker/cql/docker-compose.yml
test/package.json

There was some special logic in the CQL driver code that turned all objects
into strings. This would cause an error when an array (treated as an object
in Javascript) function was called; which would only happen when the
database had a user-defined function (UDF).
This commit removes this logic and adapts the Docker tests to include a
UDF.
Closes #495
----

Fix Cassandra driver fail after creating UDF

---

packages/drivers/src/driver/oracle/index.ts

Similar to #344, except for Oracle DB.
```sql
SELECT HEXTORAW('67453E129BE8D312A456426655440000') FROM DUAL;
```
**Before**
```
{
"data": [
103,
69,
62,
18,
155,
232,
211,
18,
164,
86,
66,
102,
85,
68,
0,
0
],
"type": "Buffer"
}
```
**After**
```
67453E129BE8D312A456426655440000
```
Format is the same as Oracle SQL Developer's.

Oracle DB: Improve display of RAW columns

---

packages/extension/index.ts
packages/plugins/connection-manager/extension.ts

Signed-off-by: Shimon Ben.Yair <shimon.ben.yair@sap.com>
This PR fixes the problem that after adding a new connection (for example sqlite/hana) it is being saved in the settings.json and is displayed ok,  but after refresh it disappears.
Close #530
----

Fix disappearing connections after browser refresh in Theia #530

---

packages/drivers/src/driver/pgsql/index.ts

The catch block within the query method of index.js did not release clients back to the connection pool. This resulted in clients not being released back to the pool after a failed query, and therefore becoming unusable or dead clients.

Update pgsql/index.js query() Catch Block

---

packages/drivers/src/driver/cql/index.ts
packages/drivers/src/driver/cql/legacy/queries.ts
packages/drivers/src/driver/cql/queries.ts
test/docker/cql/Dockerfile.cassandra
test/docker/cql/docker-compose.yml
test/docker/docker-compose.yml
test/package.json
test/project.code-workspace

Upon connection to a CQL database, a query is run to check for compatibility
with a modern schema. If not found, compatibility with Cassandra versions prior
to 3.0 is assumed. This includes making the correct schema queries,
validator-to-type transformation, and not using `GROUP BY` to count columns
per table.
Aside from that, this commit includes improvements to driver code readability
and makes all columns explicit in queries.
Fixes #548
----

Add support to legacy CQL schemas

---

packages/extension/package.json

This PR adds autocomplete support for `sqltools.format.reservedWordCase` settings. 
```json
"enum": [
"upper",
"lower",
"null"
]
```
----

Added enum for sqltools.format.reservedWordCase

---

packages/plugins/connection-manager/explorer/SidebarItem.ts
packages/types/index.d.ts

Describe here what is this PR about and what we are achieving merging this.
`Add Name(s) to Cursor` may expect `snippet` string, which I would like to use in my custom driver. So, I just added this field to SidebarItem.
----

Added snippet for SidebarItems

---

packages/driver.mysql/src/ls/queries.ts

When setting up a MySQL connection, the order of the databases in the drop down list is not sorted. This simply orders the list
alphabetically to quickly find the desired database if one connection has multiple databases associated with it. 
----

Sort MySQL databases alphabetically

---

packages/formatter/package.json

package.json of @sqltools/formatter has an incorrect path to .d.ts file. This PR fixes that.
----

Fix the path to .d.ts

---

packages/formatter/README.md

Fix README import usage for `@sqltools/formatter` package. Details see #733 
----

Fix README for sqlFormatter package

---

packages/plugins/connection-manager/screens/results.ts

When the result opens, the entire query text is pasted into the tab label. It makes it extremely annoying to use as even to find the close tab button, one has to scroll horizontally the entire length of the query.
Below screenshot before
and after

Truncate query text not to explode result tab
